stages:
  - build
  - test
  - deploy

image: buildkite/puppeteer

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run dist
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - mkdir -p dist
    - npm test

deploy:
  stage: deploy
  when: manual
  script: echo 'deploy test'
  environment:
    name: production
  dependencies:
    - build
