stages:
  - test
  - dist
  - deploy

image: node:latest

before_script:
  - npm install

test:
  stage: test
  script:
    - yarn test

dist:
  stage: dist
  script:
    - yarn run dist

deploy:
  stage: deploy
  when: manual
  script: echo 'deploy test'
  environment:
    name: production
