import BambooService from 'core/services/bamboo/buildService';
import BuildBotService from 'core/services/buildbot/buildService';
import CctrayService from 'core/services/cctray/buildService';
import CruiseControlNetService from 'core/services/cruisecontrol.net/buildService';
import CruiseControlRBService from 'core/services/cruisecontrol.rb/buildService';
import CruiseControlService from 'core/services/cruisecontrol/buildService';
import GoService from 'core/services/go/buildService';
import JenkinsService from 'core/services/jenkins/buildService';
import SnapService from 'core/services/snap/buildService';
import TeamCityService from 'core/services/teamcity/buildService';
import TravisService from 'core/services/travis/buildService';
import badgeController from 'core/badgeController';
import buildkite from 'services/buildkite/buildkite';
import chromeListeners from 'core/chromeListeners';
import jenkins2 from 'services/jenkins2/jenkins2';
import logger from 'core/logger';
import notificationController from 'core/notificationController';
import passwordExpiredHandler from 'core/passwordExpiredHandler';
import poolingService from 'services/poolingService';
import serviceConfiguration from 'core/config/serviceConfiguration';
import serviceController from 'core/services/serviceController';
import serviceView from 'core/services/serviceView';
import viewConfiguration from 'core/config/viewConfiguration';

serviceConfiguration.init();
viewConfiguration.init();
logger.init();
badgeController.init();
notificationController.init({ timeout: 5000, configuration: viewConfiguration.changes });
serviceView.init();
chromeListeners.init();
passwordExpiredHandler.init();

serviceController.clear();
serviceController.registerType(BambooService);
serviceController.registerType(BuildBotService);
serviceController.registerType(poolingService.create(buildkite));
serviceController.registerType(CctrayService);
serviceController.registerType(CruiseControlService);
serviceController.registerType(CruiseControlNetService);
serviceController.registerType(CruiseControlRBService);
serviceController.registerType(GoService);
serviceController.registerType(JenkinsService);
serviceController.registerType(poolingService.create(jenkins2));
serviceController.registerType(SnapService);
serviceController.registerType(TeamCityService);
serviceController.registerType(TravisService);

serviceController.start(serviceConfiguration.changes);
